{% set version = "2.1.0" %}

package:
  name: charls
  version: {{ version }}

source:
  url: https://github.com/team-charls/charls/archive/{{ version }}.tar.gz
  sha256: 0d6af23928ba4f1205b1b74754111e5f5f6b47d192199ffa7a70d14b824ad97d
  patches:
    - remove_dll_import_definitions.patch

build:
  skip: True  # [win and vc<14]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make   # [not win]
    - ninja  # [win]

test:
  commands:
    - test -f $PREFIX/lib/libCharLS${SHLIB_EXT}     # [unix]
    - test -f $PREFIX/include/CharLS/charls.h       # [unix]
    - test -f $PREFIX/include/CharLS/publictypes.h  # [unix]
    - if not exist %LIBRARY_LIB%\\CharLS.lib exit 1             # [win]
    - if not exist %LIBRARY_BIN%\\CharLS.dll exit 1             # [win]
    - if not exist %LIBRARY_INC%\\CharLS\\charls.h exit 1       # [win]
    - if not exist %LIBRARY_INC%\\CharLS\\publictypes.h exit 1  # [win]

about:
  home: https://github.com/team-charls/charls
  license: BSD-3-Clause
  license_family: BSD
  # License file name will change to LICENSE.md in 2.1.0
  # license_file: LICENSE.md
  license_file: License.txt
  summary: 'CharLS is a C++ implementation of the JPEG-LS standard for lossless and near-lossless image compression and decompression. JPEG-LS is a low-complexity image compression standard that matches JPEG 2000 compression ratios.'

extra:
  recipe-maintainers:
    - hmaarrfk
